# POST http://172.20.10.6:8080/User/login.php HTTP/1.1
# content-type: application/json

# {
#      "MAIL": "test@test.fr",
#      "MDP": "test"
#  }


# POST http://172.20.10.6:8080/livres/get.php HTTP/1.1
# content-type: application/json

# {
#     "user_id": "37"
# }


POST http://172.20.10.6:8080/livres/getSouhait.php HTTP/1.1
content-type: application/json

{
    "user_id": "37"
}